<?php
// config/governorates.php
return [
    'cairo'         => 'cairo',
    'giza'          => 'giza',
    'alexandria'    => 'alexandria',
    'dakahlia'      => 'dakahlia',
    'red sea'       => 'red sea',
    'beheira'       => 'beheira',
    'fayoum'        => 'fayoum',
    'gharbia'       => 'gharbia',
    'ismailia'      => 'ismailia',
    'monufia'       => 'monufia',
    'minya'         => 'minya',
    'qalyubia'      => 'qalyubia',
    'new valley'    => 'new valley',
    'suez'          => 'suez',
    'aswan'         => 'aswan',
    'assiut'        => 'assiut',
    'beni suef'     => 'beni suef',
    'port said'     => 'port said',
    'damietta'      => 'damietta',
    'sharkia'       => 'sharkia',
    'south sinai'   => 'south sinai',
    'kafr el sheikh'=> 'kafr el sheikh',
    'matrouh'       => 'matrouh',
    'luxor'         => 'luxor',
    'qena'          => 'qena',
    'north sinai'   => 'north sinai',
    'sohag'         => 'sohag',
];
